export default {
  layoutDesktop: "2x1",
  layoutMobile: "2x1",
  enableHoverCTA: false,
  enableHoverWithArrowIcon: false,
  positioningDesktop: "alignLeft alignTop",
  positioningMobile: "alignLeft alignTop",
  frontSide: {
    title: {
      title: "Lorem Ipsum Dolor sit amet",
      titleBackgroundColorDesktop: "#000",
      titleBackgroundColorTablet: " #000",
      titleBackgroundColorMobile: "#000",
      titleFontSizeDesktop: "24",
      titleFontSizeTablet: "24",
      titleFontSizeMobile: "16",
    },
    headerTag: "h3",
    description: {
      description:
        "Sorade neroskap. Mävis revis. Änis hexaheten. Bovis nil. Intranat aheten. Ratt nesk. Rugt oktig. Hemir eneras. Bev sedat.",
      descriptionBackgroundColorDesktop: "#000",
      descriptionBackgroundColorTablet: "#000",
      descriptionBackgroundColorMobile: "#000",
      descriptionFontSizeDesktop: "14",
      descriptionFontSizeTablet: "14",
      descriptionFontSizeMobile: "14",
      descriptionLineHeightDesktop: "18",
      descriptionLineHeightTablet: "18",
      descriptionLineHeightMobile: "18",
    },
    cta1: {
      type: "categoryPicker",
      url: "",
      label: "CTA 1",
      colorFontDesktop: "#000",
      colorFontTablet: "#000",
      colorFontMobile: "#000",
    },
    cta2: {
      type: "categoryPicker",
      url: "",
      label: "CTA 2",
      colorFontDesktop: "#000",
      colorFontTablet: "#000",
      colorFontMobile: "#000",
    },
    mediaType: {
      image: {
        imageDesktop: "/clientlib-resources/images/product-img-2x2.jpg",
        imageTablet: "/clientlib-resources/images/product-img-2x2.jpg",
        imageMobile: "/clientlib-resources/images/product-img-2x2.jpg",
        altTextImage: "alt editorial",
      },
      background: {
        bgColorDesktop: " ",
        bgColorTablet: " ",
        bgColorMobile: " ",
      },
      type: "image",
    },
  },
  backSide: {
    enableBackSide: false,
    title: {
      title: "Lorem Ipsum Dolor sit amet",
      titleBackgroundColorDesktop: "#fff",
      titleBackgroundColorTablet: "#fff",
      titleBackgroundColorMobile: "#fff",
      titleFontSizeDesktop: "24",
      titleFontSizeTablet: "24",
      titleFontSizeMobile: "15",
    },
    headerTag: "h2",
    description: {
      description:
        "Sorade neroskap. Mävis revis. Änis hexaheten. Bovis nil. Intranat aheten. Ratt nesk. Rugt oktig. Hemir eneras. Bev sedat.",
      descriptionBackgroundColorDesktop: "#fff",
      descriptionBackgroundColorTablet: "#fff",
      descriptionBackgroundColorMobile: "#fff",
      descriptionFontSizeDesktop: "14",
      descriptionFontSizeTablet: "14",
      descriptionFontSizeMobile: "14",
      descriptionLineHeightDesktop: "18",
      descriptionLineHeightTablet: "18",
      descriptionLineHeightMobile: "18",
    },
    backgroundColorDesktopBackSide: "#4E555A",
    backgroundColorTabletBackSide: "#4E555A",
    backgroundColorMobileBackSide: "#4E555A",
    cta1: {
      url: "",
      label: "CTA 1",
      colorFontDesktop: "#fff",
      colorFontTablet: "#fff",
      colorFontMobile: "#fff",
    },
    cta2: {
      url: "",
      label: "CTA 2",
      colorFontDesktop: "#fff",
      colorFontTablet: "#fff",
      colorFontMobile: "#fff",
    },
  },
};
